### ISSUE TITLE
2D data set use case possibility?

### ISSUE THREAD

**Issue by mukeshnarendran7** [MartinXM/LST#1]
Hi, thanks for sharing your work and I am interested in trying to another application. I am aware that the dataset is based on 3D co-ordinates but I have a 2D pose dataset. Will it be possible to incorporate that data to train this model using transfer learning? If yes, how can i do so?Thanks

**Comment by MartinXM** [comment]
2D pose to 3D joints transfer learning is an interesting topic. However, the 2D and 3D datasets have different input dimensions, maybe you need to tackle that first.
