### ISSUE TITLE
About Bone modality

### ISSUE THREAD

**Issue by XIDIANPQZ** [MartinXM/LST#5]
Thanks for the great work！

When I trained the bone modality following the Readme， I found the modality still is joint.
In the config, the "bone" is set to False.
And the running command `CUDA_VISIBLE_DEVICES=0,1 python main_multipart_ntu.py --config config/nturgbd120-cross-subject/lst_bone.yaml --model model.ctrgcn.Model_lst_4part_bone --work-dir work_dir/ntu120/csub/lst_bone --device 0 1
` does not change this setting.

**Comment by MartinXM** [comment]
We use k=1 to change the modality, similar to InfoGCN

**Comment by XIDIANPQZ** [comment]
Thank you
